networks:
  fastapi_network:
    driver: bridge

volumes:
  fastapi_volume:

services:
  db:
    image: postgres:17.4-alpine3.21
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - fastapi_network
    volumes:
      - fastapi_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fastapi_network
    volumes:
      - ./app/logs:/api/app/logs
