# Use a imagem oficial do Python versão 3.12 como imagem base
FROM python:3.12

# Define o diretório de trabalho para /api
WORKDIR /api

# Configuração de variáveis de ambiente
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/"


# Instalação do Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Adiciona o executável do Poetry ao PATH
ENV PATH="/root/.local/bin:$PATH"

# Copia os arquivos poetry.lock e pyproject.toml para o diretório de trabalho
COPY ./poetry.lock .
COPY ./pyproject.toml .

# Configuração do Poetry e instalação das dependências
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

# Copia o conteúdo do diretório ./app para o diretório /api na imagem
COPY ./app /api/app

# Define o comando padrão para rodar a aplicação
CMD ["python", "./app/main.py"]

# Exponha a porta 5000
EXPOSE 5000
